apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: devops-sample
  namespace: kube-public
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate :
      maxUnavailable: 0%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: devops-sample
    spec:
      containers:
      - name: devops-sample
        image: hub.docker.com/r/avivd/devops-sample/
        envFrom:
        - configMapRef:
            name: devops-sample-config
        ports:
        - containerPort: 4567
